require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'BookReader' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.80.0' })
    pod 'RNSearchBar', :path => '../node_modules/react-native-search-bar'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end
